services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    restart: unless-stopped
    ports:
      - "8034:8034"
    networks:
      - db-server-net
    environment:
      DB_HOST: app_postgres     # external Postgres container
      DB_PORT: 5432
      DB_USER: kit
      DB_PASSWORD: admin123Pw
      DB_NAME: knightindustrytech
    # depends_on removed because Postgres is external
    # entrypoint.sh will handle waiting

networks:
  db-server-net:
    external: true
    name: db-server_default
