version: "3.9"

services:
  paypal-payments:
    container_name: paypal-payments
    build:
      context: .
      dockerfile: Dockerfile
    image: paypal-payments:latest
    restart: unless-stopped
    ports:
      - "8800:8800"
    networks:
      - db-server-net

networks:
  db-server-net:
    external: true
    name: db-server_default
